language: python
python:
  - 2.7
  - 3.5
  - nightly
install:
  - pip install pytest
  - pip install coveralls
  - pip install pyyaml
  - pip install jinja2
  - pip install six  # for testing only
script:
  make test.report
after_success:
  coveralls
