python:
  - "2.7"
  - "3.3"
  - "nightly"
sudo: required
install:
  - sudo pip install pytest
  - sudo pip install pyyaml
  - sudo pip install coveralls
script:
  make test
after_success:
  coveralls
